### PR TITLE
Batching with persistent buffers

### PR DESCRIPTION
**Pull request by miquelmiro3**

### CODE REVIEW

**Review by monikamnc — CHANGES_REQUESTED** [review]
I think we don't have to load the .metas because we are going to redo them with RM PR or did you uploaded for some reason? 
Let's ask @Bernatmago just in case if you want.

You will see the comments related with the generated files, I think we have to erase them.
Let's ask @baransrc just in case if you want.

Testing this pr I found some strange bugs:
One while loading bunny and adding the normal texture provokes the skybox become black, this is a normal thing or is a bug?
The other one was related with the miniatures of the textures on the inspector.

**Review by Bernatmago — APPROVED** [review]
Glad to see batching being released, u really did a great job with this <3

**Comment by Bernatmago** [comment]
> 

Hi monica I updated all the assets to current dev ones

**Review by monikamnc — APPROVED** [review]

**Review by Bernatmago — CHANGES_REQUESTED** [review]
I broke something with the develop changes here, dont merge yet

**Review by Bernatmago — APPROVED** [review]

**Pull request merged**
