### PR TITLE
Bugfix dont save scene on play mode

### PR DESCRIPTION
**Pull request by alvarosoppelsa**
- Add autosave checkbox in windows configuration and save it on setting file he.cfg
- When closing the engine and is playing, first load temp_scene.scene then save it
- File temp_scene.scene is now saved in library/scenes to avoid tracking it

### CODE REVIEW

**Comment by miquelmiro3** [comment]
I just took a quick look, but those this solve the not save the "play mode" scene (the changes u make while in play mode should not be saved).

**Comment by alvarosoppelsa** [comment]
> I just took a quick look, but those this solve the not save the "play mode" scene (the changes u make while in play mode should not be saved)?

The PR's name is confusing now I read it again. If I understood well, the bug was that if you close the engine while in play mode, the scene that was saved was the play mode one and not the one you see once you press the stop button (saved in temp_scene.scene). @baransrc pls let me know if that is ok
With this fix, once you close the engine, if is in play mode, first will load temp_scene.scene and then it will save it. 
Also I added two more things that I'd like your approval, the autosave checkbox in WindowConfiguration and save temp_scene.scene in library/scenes instead of assets/scenes.
Thanks!

**Review by miquelmiro3 — APPROVED** [review]

**Comment by baransrc** [comment]
> > I just took a quick look, but those this solve the not save the "play mode" scene (the changes u make while in play mode should not be saved)?
> 
> The PR's name is confusing now I read it again. If I understood well, the bug was that if you close the engine while in play mode, the scene that was saved was the play mode one and not the one you see once you press the stop button (saved in temp_scene.scene). @baransrc pls let me know if that is ok
> With this fix, once you close the engine, if is in play mode, first will load temp_scene.scene and then it will save it. 
> Also I added two more things that I'd like your approval, the autosave checkbox in WindowConfiguration and save temp_scene.scene in library/scenes instead of assets/scenes.
> Thanks!


Yes it should behave just like you've said. I will review your pr this evening :)

**Comment by alvarosoppelsa** [comment]
Thx!!

**Review by baransrc — APPROVED** [review]
Thanks for the good work! Looks good to me.

**Review by Bernatmago — APPROVED** [review]

**Pull request merged**
