### PR TITLE
Improved lasers.

### PR DESCRIPTION
**Pull request by bernatgb**
I have changed the material of the lasers and have added some sparks when it collides with some parts of the level.

### CODE REVIEW

**Review by Izenz — CHANGES_REQUESTED** [review]
Hey!

The lasers look very cool but the game crashed when I tried hitting an enemy.
CombatManager in Level2.scene is missing the script TimeManager, which yields an exception when trying to call a method from that script after hitting an enemy.

I think if you add it it will work again.

Cheers!

**Comment by bernatgb** [comment]
> Hey!
> 
> The lasers look very cool but the game crashed when I tried hitting an enemy.
> 
> * CombatManager in Level2.scene is missing the script TimeManager, which yields an exception when trying to call a method from that script after hitting an enemy.
> 
> I think if you add it, everything will work again.
> 
> Cheers!

Thanks, looks like someone had removed the script previously because it's not in development either.

**Review by Izenz — APPROVED** [review]
It appears to be working now.

Cheers!

**Comment by Bernatmago** [comment]
Good job!

**Pull request merged**
