### PR TITLE
Player feedbacks

### PR DESCRIPTION
**Pull request by alvarosoppelsa**
Add feedback vfx & sfx when Player receives damage.
For vfx, a new billboard orientation was needed without taking into account camera projection, thats why there are some changes in the components.
Fos sfx, it was needed to tell the damage causer when calling RegisterHit, so you will see a new parameter in this function

### CODE REVIEW

**Review by monikamnc — CHANGES_REQUESTED** [review]
Hello!

Visual Studio shows some errors on animation variables, I don't know if it's maybe because there's missing some update from dev?
image

image

image

When I compiled it the level 1 was without the IBL activated / compiled, also the rotation changes are because of the script changes of quaternions that we implemented or other reason?
Because I saw so many changes from 0 to -0, 180 to -180 and vice versa.

Thanks!

**Comment by alvarosoppelsa** [comment]
> Hello!
> 
> Visual Studio shows some errors on animation variables, I don't know if it's maybe because there's missing some update from dev? image
> 
> image
> 
> image
> 
> When I compiled it the level 1 was without the IBL activated / compiled, also the rotation changes are because of the script changes of quaternions that we implemented or other reason? Because I saw so many changes from 0 to -0, 180 to -180 and vice versa.
> 
> Thanks!

Ok, I'll take a look. Thanks!

**Comment by alvarosoppelsa** [comment]
I couldn't reproduce this errors. It's weird since ComponentAnimation is in gampleypch. Did you try with full clean before build?
About rotation changes, were done automatically when I saved the level, I can try to undo those changes manually if they are causing some kind of issue

**Review by monikamnc — APPROVED** [review]
It seems it's only me the one I see the errors :/ 
I approve to don't block the pr

**Review by miquelmiro3 — APPROVED** [review]
It works in my side, good job it feels much better! I think i am missing the sound on the fall but i saw that is intentional

**Comment by alvarosoppelsa** [comment]
@miquelmiro3 it felt kind of weird for me to use the same audio than damage.. I'll take note to have an specific fall sfx

**Pull request merged**
