### PR TITLE
Boss crystalization in center

### PR DESCRIPTION
**Pull request by miquelmiro3**
When boss enters to the crystalization phase (cacoon), it walks to the center to do it. It would be cool to make him jupm there but for now lets have a base that is solid. Also added an obstacle component to the boss so player and enemies cant move him at the start and during cacoon.

Also i updated the crystals so they explode instantly by hit. It was a small change and i didnt feel it need it its own pr.

### CODE REVIEW

**Review by VBoschMatas — APPROVED** [review]

**Review by Bernatmago — CHANGES_REQUESTED** [review]
Merged dev to it and its crashing, i know its probably not ur fault but we need to fix it uwu
image

**Comment by VBoschMatas** [comment]
> Merged dev to it and its crashing, i know its probably not ur fault but we need to fix it uwu image

In theory now its fixed, if you can, test it again

**Comment by miquelmiro3** [comment]
> > Merged dev to it and its crashing, i know its probably not ur fault but we need to fix it uwu image
> 
> In theory now its fixed, if you can, test it again

love u @VBoschMatas

**Comment by Bernatmago** [comment]
> Reference in

Was still crashing for me there were un commited assets that kept changing Id Im merging dev and lets see what happens

**Review by Bernatmago — APPROVED** [review]
Working after merge gj

**Pull request merged**
