### PR TITLE
[BLOCK_SCENES] Level 1 & 2 camera improvements + Level 1 Navmesh change

### PR DESCRIPTION
**Pull request by VBoschMatas**
**THIS PR ACTS ON LEVEL 1 AND LEVEL 2 SCENES, AND LEVEL 1 SCENE CHANGES ARE BIG, you will need to download the latest .fbx of the scene here:**  https://drive.google.com/file/d/1q1eDNvTwOgOnP32bo0LK9YBtkVF8ASV5/view. 
Each zone has a different camera distance/angle.
Gauntlets have a camera that allows the visualization of most of the gauntlet at the same time.
How to test it: idk, just play the game I guess, and check that alll cameras are fine and help the player.

### CODE REVIEW

**Comment by VBoschMatas** [comment]
For those of you wandering why the navmesh cahnge is here, it was just time optimization, camera changes were big on sceene so is navmesh, and istead of witing for this to merge I made both changes here. Sorry

**Comment by Izenz** [comment]
As we talked in Discord the camera is a bit buggy when the player drops to 1 HP in one of the places where the camera moves back for a wider vision. The rest is very good tho, the angles and the camera distance for some places are very good for the player to see everything that it needs to see.

Good work!

**Review by Izenz — CHANGES_REQUESTED** [review]
In Level 2, if you reach the Boss entrance and go back while dashing all the time the camera breaks. Reach me out on Discord for more info.

**Review by armandojaga — APPROVED** [review]

**Review by Bernatmago — APPROVED** [review]
Mega amazing job man, all working great. I managed assets a bit but but everything else perfect

**Pull request merged**
