### PR TITLE
Updating module input API

### PR DESCRIPTION
**Pull request by armandojaga**
Improving the logic to detect when a key has been pressed, as well as the mouse buttons

### CODE REVIEW

**Review by Bernatmago — APPROVED** [review]

**Comment by Bernatmago** [comment]
I fixed a bug where mouse motion was mantained if no motion events appeared. Also returned position to the old imgui logic because camera was less smooth and extremelly slow (was very not smooth when scaling up speed for some reason). Lastly i brought back the pixels motion tracking because it was the unit being used in some places and it had been changed to move in normalized values which would have caused headaches on gameplay.

Liked the new functionality, hope you don't mind i just thought it would be more efficient this way

**Review by alvarosoppelsa — APPROVED** [review]

**Review by baransrc — CHANGES_REQUESTED** [review]
Thanks for the work. I'm leaving a change request to block this from accidentally being merged before addressing the issues the changes we've talked about in the discord server. Some previously working mouse position related functionalities are not working as intended right now.

**Comment by armandojaga** [comment]
@baransrc please check the latest changes, since your change request is blocking the merge

**Comment by baransrc** [comment]
> @baransrc please check the latest changes, since your change request is blocking the merge

Hey, sorry for being this late, I've reviewed and tested the changes again and turns out we missed the normalized mouse position api which we were using for camera movement on scripts. I've added the calculation of normalized mouse positions, and the api to get those from scripting. Other than that, thanks for your hard work and the improvements on the API. I'm proceeding with approving this PR, but you are free to review my changes and in case of any weirdness or bug, we can fix those as well before merging this PR. If you want to test the changes I've made and its effects on scripting side, dm me and I can send you a ready made scene for testing this PR. ❤️‍🔥

**Review by baransrc — APPROVED** [review]

**Pull request merged**
