### PR TITLE
Improve melee & bunch other combat changes

### PR DESCRIPTION
**Pull request by VBoschMatas**
- **All weapons changed**
  - Melee = worst one
  -  Claws = faster chains
  -  Sword = Big damage, big range
  -  Hammer = Big damage, bigger range, slower combos.

- Camera feedback improved on both melee and ranged attacks.
- Vignete added when having low health and dying
- Camera effects on low health and dying
- New animations for all the attacks
- **Just in Level 1** updated the trails of the attacks. PLESE TELL ME IF YOU LIKE THEM SO I CHANGE THEM IN ALL THE LEVELS.

### CODE REVIEW

**Review by miquelmiro3 — APPROVED** [review]

**Comment by miquelmiro3** [comment]
Vicenç u are a fricking god, it feels muuuuuch better and all the camera movements are great! The only thing i am missing is that the 3rd attack withour weapon does not has a trail and that when the player attack fast the animation and the trail are not syncronized. Except that soooo much better, really good job!

**Comment by VBoschMatas** [comment]
> Vicenç u are a fricking god, it feels muuuuuch better and all the camera movements are great! The only thing i am missing is that the 3rd attack withour weapon does not has a trail and that when the player attack fast the animation and the trail are not syncronized. Except that soooo much better, really good job!

Yeah, trails can and will be improved, here I just adjusted the previously existing ones.

**Review by bernatgb — APPROVED** [review]
Wow, amazing job!!!! Totally agree with Miquel about you being a god and about the comments regarding the trails.

**Comment by VBoschMatas** [comment]
Added a scuffed 3rd trail for melee and applied trail changes to all scenes

**Pull request merged**
