### PR TITLE
[BLOCK LEVEL] Added spores to plants.

### PR DESCRIPTION
**Pull request by bernatgb**
Spores and dustwind that Phan requested me to add.

Spores are on bulbs and the dustwind appears while playing.

### CODE REVIEW

**Review by ermario — CHANGES_REQUESTED** [review]
Spores look good, maybe they should be more blended with the environment (set some alpha and slow them down a bit) we can check that with the artist for some feedback. 
What I don't see appropriate is the wind effects (leafs and dust) they don't match at all and they are annoying while playing. I would delete them. I already created some dust particles in my branch that I will add. If more needed I will take care on that.
Thank you!

**Review by Izenz — COMMENTED** [review]
The spores look good but the dust wind looks a little bit weird in my opinion, it appears and disappears way too abruptly. Perhaps it could be improved by adding some wind sound effect when its on.

Right now I feel like its something that just gets in the way of the player's vision rather than something that adds to the immersion of the scene.

**Review by miquelmiro3 — APPROVED** [review]

**Review by Izenz — APPROVED** [review]
Remember to remove the assets from the dust wind if we are not using them

**Review by Bernatmago — CHANGES_REQUESTED** [review]
I fixed prefab texture that got broken somehow on merge and placed them on latest level but they seem to be less noticeable and Idk what changed. Im sure you will find it quickly 
image

**Review by Bernatmago — APPROVED** [review]

**Pull request merged**
