### PR TITLE
Adding tour for level 2

### PR DESCRIPTION
**Pull request by armandojaga**
This moves the camera around for the level tour on level 2

### CODE REVIEW

**Review by bernatgb — COMMENTED** [review]
That's what I see:

https://user-images.githubusercontent.com/33035442/197759994-4cf82cb7-b353-4494-a2e8-c5bc07c29610.mp4

**Comment by armandojaga** [comment]
> That's what I see:
> tourlvl2.mp4

Can you try again, I just did a rebase

**Review by bernatgb — APPROVED** [review]
I can see it properly now, good job!

**Review by baransrc — APPROVED** [review]
Everything looks good, thanks for the good work, I'm merging this branch right now to unblock @monikamnc 's tasks tomorrow.

**Pull request merged**
