### PR TITLE
Improvement/enemies disappearing with alpha transitions

### PR DESCRIPTION
**Pull request by bernatgb**
Now the enemies disappear softly with an alpha transition.

Also added to the player a component agent to avoid overlapping with the enemies but not with the parasites in order to be able to pick them up.

(In scene Level is set up correctly, if you want to test it in another scene be sure that player has the component agent and the checkbox Player agent set to true, and the materials of the enemies set to transparent instead of opaque.)

### CODE REVIEW

**Comment by miquelmiro3** [comment]
Is a bit strange making enemies obstacles when dead, is that a design decision??

**Review by miquelmiro3 — APPROVED** [review]

**Comment by bernatgb** [comment]
> Is a bit strange making enemies obstacles when dead, is that a design decision?? And spamming F key make you receive a parasite before the enemy disapears. Beside that all good

The reason is to avoid the player could overlap enemies when they are dead. The receiving parasite problem happened always, now it becomes clearer since the enemy takes longer to disappear. I will try to solve it.

**Comment by monikamnc** [comment]
> Is a bit strange making enemies obstacles when dead, is that a design decision?? And spamming F key make you receive a parasite before the enemy disapears. Beside that all good

The version before has some bugs that made the bug "dance" orbiting you and doesn't stay in the position they died. We can leave it like this now and ask the design team if they want to change it and we can change it after alpha presentation.
You are right, maybe we have to wait to change the status to parasite to don't allow the player catch the parasite before it shows.

**Comment by Bernatmago** [comment]
If the player is already an agent wouldnt it make sense to keep the agent alive to prevent overlapping? Obstacle + agent is very overkill

**Review by Bernatmago — CHANGES_REQUESTED** [review]
I dont like the obstacle thing, we should think about an easy solution it feels like a workaround

**Comment by Bernatmago** [comment]
Found a solution to obstacle ill be pushing it here

**Comment by bernatgb** [comment]
> I dont like the obstacle thing, we should be able to walk over dead enemies

I thought that would be better if the player can't traspas dead enemies, but I if we do it like you say we can delete the obstacle and that's it.

**Review by Bernatmago — APPROVED** [review]
Fixed the obstacle thing and made the parasyte drop before enemmy fades out (it slowed the game a lot). Been having issues with parasyte being invisible untill bug disapears but we can fix later

**Comment by Bernatmago** [comment]
> > I dont like the obstacle thing, we should be able to walk over dead enemies
> 
> I thought that would be better if the player can't traspas dead enemies, but I if we do it like you say we can delete the obstacle and that's it.

Changed it, test when you can to confirm everything is ok

**Pull request merged**
