### PR TITLE
Feature/boss animations

### PR DESCRIPTION
**Pull request by Erick9Thor**
This PR includes: 

- Updated all animations and added new Boss model with the textures.
- Fixes Playetest Fedback 25/10/2022 (https://docs.google.com/document/d/1_ozq7MWhEIdfm2C28TCIvOB-1_yNfxUpfWCc3hzxB54/edit)

### CODE REVIEW

**Review by bernatgb — COMMENTED** [review]
Sometimes the boss instead of walking just slides.

**Comment by Erick9Thor** [comment]
> Sometimes the boss instead of walking just slides.

Fixed

**Comment by Bernatmago** [comment]
Boss is still doing 2 dmg please change it

**Review by Bernatmago — APPROVED** [review]
I feel like there ar eperiods of time where the boss should be hitable and its sometimes not? When it lands on its belly for example. He also tries geting too close for a melee attack which we should fix. And also change all the damages to 1.

Gj tho, looking better now!

**Review by monikamnc — APPROVED** [review]
Haven't test just cleaning PRs

**Pull request merged**
