### PR TITLE
Added the new effects and updated existing Explosive crystals

### PR DESCRIPTION
**Pull request by EdwardRegasDuncan**
Modified: 
Level 1: Explosive Crystals
Boss Level: Explosive Crystal pool

### CODE REVIEW

**Review by bernatgb — CHANGES_REQUESTED** [review]
I don't see any textures on either the explosive crystals or the prefab.

**Comment by miquelmiro3** [comment]
Could you list in the description the assets that are changed because i see some white billboards but i dont know if those are yours.

**Comment by bernatgb** [comment]
> Could you list in the description the assets that are changed because i see some white billboards but i dont know if those are yours.

I see the same.

**Review by Bernatmago — CHANGES_REQUESTED** [review]
Its conflicting with the current scene which has a lot of changes, we can create a prefab with all of them or something to place in the new scene version

**Review by Bernatmago — APPROVED** [review]

**Pull request merged**
