### PR TITLE
Combat feel

### PR DESCRIPTION
**Pull request by VBoschMatas**
**WIP**

Combat experience improved, with better fluidity.
Lock times reduced, weapons' hit boxes fit more into their animations.

Working on slight improvements on ranged attacks

### CODE REVIEW

**Comment by alvarosoppelsa** [comment]
Hey @VBoschMatas I think the fluidity can be felt, good job! I'd like to test it more with the last changes on dev, what do you say if we merge dev it into this branch?

**Comment by monikamnc** [comment]
The changes you are doing feels great while playing.
I have updated the gamepad controls as you requested:
- Melee Attack with X.
- Range Attack with RB or LB.
- Moved Pickup Parasite to B.

Hope with this we can start all testing with gamepad better.

**Review by monikamnc — APPROVED** [review]
Thank you for your work ^-^

**Review by miquelmiro3 — APPROVED** [review]
Good job, it feels much better! Just two comments one about the sound, a part of being weird, i don't know when it is triggered, it feels that is out of time or that with the sword there are much more sound triggers. And the other thing would be that if you click 4 times in a row, u execute the combo and then after a pause the character attacks a fourth time and it feels weird, i don't know what we should do with that.

**Review by Bernatmago — CHANGES_REQUESTED** [review]
The bullet is bugged

**Comment by VBoschMatas** [comment]
- Now attack sound only play at every attack

- Click buffer changed to be a timed buffer, it will remember the last click done in the previous 0.5 sec (can be changed if you feel we need a wider window), but a new click will override the previous buffer so if you chage clicking positions the player will change attacking direction accordingly. 

- Ranged attacks now are held with the button and you can aim wherever you want, once you release the button it will shoot (animations need updating)

**Review by Bernatmago — APPROVED** [review]

**Pull request merged**
