### PR TITLE
Sfx 5

### PR DESCRIPTION
**Pull request by alvarosoppelsa**
Sound Bank Link to test this branch (I'll upload it after merge to the drive)
https://mega.nz/file/BXdl1aiC#FsY09FePx-dZrHRM81G8EYscOh9uHLKR83zu-aGLqGQ

New SFX:
- Weapons
- Player Fall
- Lasers wall
- Crystal Spawn

Fixes
- Boss music loop
- Break cocoon call to stage 3 
- Some effects tunning

### CODE REVIEW

**Review by Bernatmago — APPROVED** [review]
AMAZING JOB ALL WORKING PERFECTLY

My only feedback is that explosive crystal doesnt really sound like an explosion/ impactful. I would love to change that but its fine if its not possible.

Thanks <3

**Comment by alvarosoppelsa** [comment]
> AMAZING JOB ALL WORKING PERFECTLY
> 
> My only feedback is that explosive crystal doesnt really sound like an explosion/ impactful. I would love to change that but its fine if its not possible.
> 
> Thanks <3

Thanks!
Wanna test now? It has some fire spell thing...

**Comment by Bernatmago** [comment]
> > AMAZING JOB ALL WORKING PERFECTLY
> > My only feedback is that explosive crystal doesnt really sound like an explosion/ impactful. I would love to change that but its fine if its not possible.
> > Thanks <3
> 
> Thanks! Wanna test now? It has some fire spell thing...

Sounds good!

**Review by baransrc — APPROVED** [review]
Everything seem to work fine, thanks the game sounds awesome!

**Pull request merged**
