### PR TITLE
New loading screen video

### PR DESCRIPTION
**Pull request by miquelmiro3**
The loading screen has change, just that.

### CODE REVIEW

**Review by bernatgb — CHANGES_REQUESTED** [review]
ComponentVideo couldn't open video file.

**Review by bernatgb — APPROVED** [review]
N
NI
NIC
NICE
NICE!

**Review by monikamnc — APPROVED** [review]
Great job, thank you ^-^

**Review by baransrc — CHANGES_REQUESTED** [review]
Thanks for the good work, however, the video doesn't loop and stationary on the second trigger of load.

**Review by armandojaga — APPROVED** [review]

**Pull request merged**
