### PR TITLE
Fixing build race condition

### PR DESCRIPTION
**Pull request by armandojaga**

### CODE REVIEW

**Comment by Bernatmago** [comment]
What was exactly happening?

**Review by Bernatmago — APPROVED** [review]

**Review by bernatgb — APPROVED** [review]

**Comment by armandojaga** [comment]
> What was exactly happening?

When you try to build the solution, it fails because it can't lock a resource

**Comment by Bernatmago** [comment]
> > What was exactly happening?
> 
> When you try to build the solution, it fails because it can't lock a resource

Weird, it was working for me but this wont hurt 👍

**Comment by armandojaga** [comment]
> > > What was exactly happening?
> > 
> > When you try to build the solution, it fails because it can't lock a resource
> 
> Weird, it was working for me but this wont hurt 👍 

If you build projects individually it won't happen, only when you build the solution

**Pull request merged**
