### PR TITLE
Exposing Component Audio Source to Scripting

### PR DESCRIPTION
**Pull request by baransrc**
This PR adds the scripting support for lovely ComponentAudioSource that @monikamnc created. Also as we have the ComponentAudioSource now, the unnecessary API's from ModuleAudio and Gameplay.h Hachiko::Audio is deleted.

### CODE REVIEW

**Review by monikamnc — APPROVED** [review]
Thank you for your help ^-^ 💙🎶

**Comment by VBoschMatas** [comment]
How do I test if this works? I tried to Add Audio Listener to the camera; Audio source, PlayerSoundManager and PlayerController to player, and I get a YAML crash on run that says it cant load the scene. Am I doing something wrong? (most probably yes)

**Review by monikamnc — APPROVED** [review]
Tested in Debug and Release and is working ;)

**Review by VBoschMatas — APPROVED** [review]
It works 👍

**Pull request merged**
