### PR TITLE
Finally, new lasers vfx!!!

### PR DESCRIPTION
**Pull request by bernatgb**
New lasers vfx for Level 2 & for boss level rotating lasers.

The laser wall is left with cylinders (colored to match the other lasers) due to the fps drop.

### CODE REVIEW

**Review by Bernatmago — CHANGES_REQUESTED** [review]
The lasers are looking cool but we should adjust some stuff
I see this weird artifact
image

And they stop in bursts for some reason, It should be a continuous line Imo

**Review by Bernatmago — CHANGES_REQUESTED** [review]
image
The hit particles dont match the new style

**Comment by bernatgb** [comment]
> The lasers are looking cool but we should adjust some stuff I see this weird artifact image
> 
> And they stop in bursts for some reason, It should be a continuous line Imo



> image The hit particles dont match the new style

This was a preliminary stage of the new sparks. Now, they are updated as well as the walking dust particles, improved to match the terrain.

**Review by Bernatmago — CHANGES_REQUESTED** [review]
The lasers are working great now and the hit effect is clean af too.

I found this with walking though: 
image

We will need to prefab the lasers and place them on the most recent scenes before merging to dev, we can help you with that just reach out on discord. Also if u need quick comunicaton bcs i never notice githug notifs sry

**Review by Erick9Thor — APPROVED** [review]
So coool man

**Review by Bernatmago — APPROVED** [review]

**Pull request merged**
