### PR TITLE
Implement ammo UI bar

### PR DESCRIPTION
**Pull request by Izenz**
Logic that controls player's ranged attack ammo.
You can test in the Level scene. Ammo should only go down when you succesfully launch a bullet, cancelling the attack should restore the ammo point back. Ammo value should not go outside the scope of [0, 4].

One point of ammo should be restored everytime the player succesfully hits a crystal or an enemy with a melee attack.

### CODE REVIEW

**Comment by alvarosoppelsa** [comment]
When I press the right mouse button fast, the bar is deleted and reloaded because the bullet hasn't been emitted. It's possible to delete the bar when shooting the bullet and not when pressing the button?

**Comment by Izenz** [comment]
Hey guys.

Yes, I will work on the UI logic to update it only when the player successfully shoots a bullet instead of having it reloaded when we cancel. I will also keep in mind to improve the hit detection to reload several bullets with one hit. I am a bit busy tonight so will do it tomorrow morning when I wake up.

Cheers!

**Comment by alvarosoppelsa** [comment]
> Hey guys.
> 
> Yes, I will work on the UI logic to update it only when the player successfully shoots a bullet instead of having it reloaded when we cancel. I will also keep in mind to improve the hit detection to reload several bullets with one hit. I am a bit busy tonight so will do it tomorrow morning when I wake up.
> 
> Cheers!

Cool! Thank you!

**Comment by Izenz** [comment]
It is far from perfect but I made a few tweaks so that UI would only update when a bullet successfully launches and amount of ammo recovered equals the number of enemies or crystals hit with a melee attack.

I didn't test much outside of a Release build (with editor) but it seemed to be working, if you find something though just let me know and I'll try to fix it as soon as possible.

**Review by miquelmiro3 — APPROVED** [review]

**Review by Bernatmago — APPROVED** [review]
Working well!

**Pull request merged**
