### PR TITLE
Boss Laser Attack

### PR DESCRIPTION
**Pull request by VBoschMatas**
Boss now has an attack that summons lasers on the entire arena and you have to use the stalactites to cover.
Some changes to lasers and stalactites (stalagmites) were done, but shouldn't affect previous behaviours.

Boss.scene may be updated or removed depending on other Boss.scene PR changes. **DO NOT MERGE THIS PR IF THE OLD Boss.scene IS PRESENT**.

For now to test it use the prefabs provided or the Boss.scene. **LaserWall and Level are a must have if you use prefabs on a different/updated scene.** For Level use the prefab _Level (Stalactites)_ and remove the parenthesis, if you dont it wont work.

### CODE REVIEW

**Comment by VBoschMatas** [comment]
Prefabs for boss level included. 
Level prefab called "Level (Stalactites)" has to have the (Stalactites) part removed, its just for differentiating the prefab in the folder.
Boss prefab's BossController has to have LaserWall linked through inspector in order to work, plus Enemy and crystal pools.

**Review by Bernatmago — APPROVED** [review]
Working great!

**Review by miquelmiro3 — APPROVED** [review]

**Review by monikamnc — CHANGES_REQUESTED** [review]
Stop until we have updated boss scene, sorry >.<

**Review by monikamnc — APPROVED** [review]
Unblocked

**Pull request merged**
