### PR TITLE
Implemented new tutorial with sounds and controller detection

### PR DESCRIPTION
**Pull request by Bernatmago**
- Tutorial has three screens
- Uses diferent screen if it detects controller
- It has sounds

How to test:
Get Level, Delete tutorial and spawn the newer tutorial prefab (old tutorial go would cash)

Will edit scene when its time to merge kisses

### CODE REVIEW

**Review by VBoschMatas — APPROVED** [review]
Coool

**Review by bernatgb — APPROVED** [review]
I'll miss Boby and Lila 😢

**Comment by VBoschMatas** [comment]
Should we wait for armando's tour merge and then change the level in this PR to include the tutorial, so anyone forgets to add it?

**Comment by Bernatmago** [comment]
> I'll miss Boby and Lila 😢

Same..

**Comment by Bernatmago** [comment]
> Should we wait for armando's tour merge and then change the level in this PR to include the tutorial, so anyone forgets to add it?

Yep will do this

**Pull request merged**
