### PR TITLE
Improvement: save rotations as angles

### PR DESCRIPTION
**Pull request by Bernatmago**
If rotation was a quaternion it is still loaded as so
All rotations are stored in euler anlges for new saves

Tested 👍

### CODE REVIEW

**Review by miquelmiro3 — APPROVED** [review]

**Review by baransrc — COMMENTED** [review]
Hey thanks for the improvement. Code is fine, but on my machine, I still have the asserts while loading the scenes, do I need to follow some specific steps to avoid them?

**Comment by Bernatmago** [comment]
> Hey thanks for the improvement. Code is fine, but on my machine, I still have the asserts while loading the scenes, do I need to follow some specific steps to avoid them?

I have not tested this, only converted level.scene so maybe u need to conver them first for it to stop happening? Its still loading quaternions on olds scenes. Its even possible that storing as angles some store a nan or something

**Review by monikamnc — APPROVED** [review]
Great thanks!

**Review by baransrc — CHANGES_REQUESTED** [review]
Testing this right now, blocked for merge to avoid merge without testing

**Review by baransrc — APPROVED** [review]

**Pull request merged**
