### PR TITLE
Drag and drop improved, Transformation naming standarized

### PR DESCRIPTION
**Pull request by VBoschMatas**

### CODE REVIEW

**Comment by Bernatmago** [comment]
Task linked: [CU-23t8g1a Improve hierarchy tree](https://app.clickup.com/t/23t8g1a)

**Review by Bernatmago — APPROVED** [review]
Excellent job mr Vicenç

**Review by monikamnc — APPROVED** [review]
Noice, Thanks

**Review by Izenz — APPROVED** [review]
Good job!

**Pull request merged**
