### PR TITLE
Pause menu and Parasite pickup tooltip

### PR DESCRIPTION
**Pull request by Izenz**
Hello!

I mixed a few of my tasks into this branch since all of them were about editing Level scenes so its easier to merge and we don't get so many conflicts. What basically changed is:

- Being close to a parasyte now displays a tooltip to the player. There should be different tooltips depending on whether we use gamepad or keyboard. Just kill an enemy and you should see text on your screen while standing next to the parasyte.
- Pause menu. It's still buggy and needs improvements BUT they are due to other scripts using Time::DeltaTime() instead of Time::DeltaTimeScaled(), we can improve it later on since we will not need to change anything in the scenes after we merge this PR (I hope... 😨)
- Also added FOG to Level2.scene under Edu's direction.

Please test the game in every way you can imagine, press Start or ESC to open up or close pause menu and just try to break it. Also any feedback on things we can add to the pause menu is appreciated.

Thanks!

### CODE REVIEW

**Review by Bernatmago — APPROVED** [review]
Somethings still move when paused but its not a big deal it makes enemies and player stop working which is enough for what we need. Also menu looking good!

For the tooltip It would be cooler to display the key on top of the parasyte in the scene but we can adapt it later. GJ!

**Review by monikamnc — CHANGES_REQUESTED** [review]
Stop until we have updated scenes >.< Sorry

**Review by monikamnc — APPROVED** [review]
Just unblock, havent test or check

**Review by baransrc — APPROVED** [review]
Thanks for the awesome contribution. As we talked via discord, we can improve stuff in later pr's. (We should fix that typo asap though hahah)

**Pull request merged**
